# Generated by Django 4.2.7 on 2023-11-13 14:36

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('n_contrato', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Número do contrato')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
                ('empresa', models.CharField(max_length=250, unique=True, verbose_name='Empresa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='n_contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desenho', models.CharField(max_length=250, verbose_name='Nº desenho')),
                ('material_de_origem', models.CharField(blank=True, max_length=250, verbose_name='Material de origem')),
                ('item', models.CharField(max_length=250, verbose_name='Item')),
                ('tag', models.CharField(max_length=250, verbose_name='Tag')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Área (m²)')),
                ('massa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Massa (kg)')),
                ('n_romaneio', models.IntegerField(blank=True, verbose_name='Nº Romaneio')),
                ('obs', models.TextField(blank=True, verbose_name='Observação')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('n_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Planejamento.contrato', verbose_name='Contrato')),
            ],
        ),
    ]
