# Generated by Django 4.2.7 on 2023-11-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planejamento', '0002_alter_contrato_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área (m²)'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='massa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Massa (kg)'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='material_de_origem',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Material de origem'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='n_romaneio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Romaneio'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
