# Generated by Django 4.2.7 on 2023-11-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planejamento', '0003_alter_componente_area_alter_componente_massa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='obs',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Observação'),
        ),
    ]
